version: '3'

services:
  autosub:
    build: .
    dockerfile: ${DOCKERFILE:-Dockerfile.gpu}
    volumes:
      - ./data/input:/input
      - ./data/output:/output
      - ./deepspeech:/deepspeech
    command: ./run.sh