version: '3'

services:
  autosub:
    build: .
    dockerfile: ${DOCKERFILE:-Dockerfile.gpu}
    volumes:
      - ${INPUT:-./data/input}:/input
      - ${OUTPUT:-./data/output}:/output
      - ./deepspeech:/deepspeech
    command: ./run.sh